version: '3.4'

services:
  redis-client:
    build: .
    image: redis-poco:latest
    environment:
      - Redis__ConnectionString=sentinel1:26379,abortConnect=true,connectTimeout=30000,responseTimeout=30000,allowAdmin=true,ssl=false,serviceName=mymaster    

networks:
  default:
    name: Humanometr_infrastructure